# Meta Data for SEO

## Homepage
title = "Christine Tham"
titleSeparator = "-"
titleAddition = "Personal Web Site"
description = "Christine Tham personal web site hosted on Github Pages."

## Documentation
# docsVersion = "0.1"

## Open Graph
images = ["doks.png"]
ogLocale = "en_AU"
domainTLD = "christinetham.github.io"
titleHome = "Christine Tham"

## Twitter Cards
twitterSite = "@chris1tham"
twitterCreator = "@chris1tham"

## JSON-LD
schemaType = "Person"
# schemaType = "Organization"
schemaName = "Doks"
schemaAuthor = "Christine Tham"
schemaAuthorTwitter = "https://twitter.com/chris1tham"
schemaAuthorLinkedIn = "https://www.linkedin.com/in/chris1tham/"
schemaAuthorGitHub = "https://github.com/ChristineTham"
schemaLocale = "en-AU"
schemaLogo = "logo-doks.png"
schemaLogoWidth = 512
schemaLogoHeight = 512
schemaImage = "doks.png"
schemaImageWidth = 1280
schemaImageHeight = 640
schemaTwitter = "https://twitter.com/chris1tham"
schemaLinkedIn = ""
schemaGitHub = "https://github.com/ChristineTham/christinetham.github.io"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [2048, 1600, 1280, 1080, 720, 480]
portraitPhotoWidths = [1280, 1080, 720, 480]
lqipWidth = "20x"
smallLimit = "300"

# Images
imageResponsive = true
imageConvertTo = "webp"
imageImageSizes = ["480","720","1080","1280","1600","2048"]
singleSize = false
imageAddClass = "img-fluid lazyload blur-up"

### Image template
defaultImage = "default-image.png" # put in `./assets/images/`
fillImage = "1270x740 Center" # normalize image size

# Footer
footer = "Copyright (c) 2022 Christine Tham"

# Feed
copyRight = "Copyright (c) 2022 Christine Tham"

# Alert
alert = true
alertDismissable = true
# alertText = "Introducing the Doks child theme, several DX + UX updates, and more! <a class=\"alert-link stretched-link\" href=\"https://getdoks.org/blog/doks-v0.2/\" target=\"_blank\" rel=\"noopener\">Check out Doks v0.2</a>"
alertText = "Currently under construction"

# Edit Page
# repoHost [Github | Gitea | GitLab | Bitbucket | BitbucketServer ] is used for building the edit link based on git hoster
repoHost = "GitHub"
#repoHost = "Gitea"
docsRepo = "https://github.com/ChristineTham/christinetham.github.io"
docsRepoBranch = "master"
docsRepoSubPath = ""
editPage = false
lastMod = false

[sections]
  sectionNav = ["docs", "blog"]

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = true
  searchSectionsShow = []
  searchSectionsIndex = ["docs", "blog"]
  darkMode = true
  bootStrapJs = true
  breadCrumb = true
  highLight = true
  kaTex = true
  multilingualMode = false
  docsVersioning = false
  fullWidth = true
  navbarSticky = true
  toTopButton = true
  scrollSpy = true # experimental; needs Bootstrap >= 5.2.0-beta1

[menu]
  [menu.section]
    auto = true
    collapsibleSidebar = true
