[[docs]]
  name = "Background"
  weight = 10
  identifier = "background"
  url = "/about/background/"

[[main]]
  name = "About"
  url = "/about/background/introduction/"
  weight = 10

[[main]]
  name = "Blog"
  url = "/blog/"
  weight = 20

[[social]]
  name = "GitHub"
  identifier = "github"
  url = "https://github.com/ChristineTham"
  post = "v0.1.0"
  weight = 10

[[social]]
  name = "Twitter"
  identifier = "twitter"
  url = "https://twitter.com/chris1tham"
  weight = 20

[[social]]
  name = "Facebook"
  identifier = "facebook"
  url = "https://facebook.com/chris1tham"
  weight = 30

[[footer]]
  name = "Privacy"
  url = "/privacy-policy/"
  weight = 10
